version: '3'

services:
  kafka:
    image: wurstmeister/kafka:latest
    ports:
      - "9092:9092"
      - "9093:9093"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_LISTENERS: INSIDE://kafka:9093,OUTSIDE://localhost:9092
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9093,OUTSIDE://localhost:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE

  zookeeper:
    image: wurstmeister/zookeeper:latest
    ports:
      - "2181:2181"

  # kafka-producer:
  #   build:
  #     context: .
  #     dockerfile: docker/Dockerfile-kafka-producer
  #   depends_on:
  #     - kafka

  # ingestion:
  #   build:
  #     context: .
  #     dockerfile: docker/Dockerfile-ingestion
  #   depends_on:
  #     - kafka
