version: '3'

services:
  kafka:
    image: wurstmeister/kafka:latest
    ports:
      - "9092:9092"
      - "9093:9093"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_LISTENERS: INSIDE://kafka:9093,OUTSIDE://localhost:9092
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9093,OUTSIDE://localhost:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_MESSAGE_MAX_BYTES: 2000000000
      KAFKA_REPLICA_FETCH_MAX_BYTES: 2000000000
      KAFKA_MAX_REQUEST_SIZE: 2000000000

  zookeeper:
    image: wurstmeister/zookeeper:latest
    ports:
      - "2181:2181"

  kafka-producer:
    build:
      context: .
      dockerfile: docker/Dockerfile-kafka-producer
    ports:
      - "8081:8080"
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
    depends_on:
      - kafka

  # ingestion:
  #   build:
  #     context: .
  #     dockerfile: docker/Dockerfile-ingestion
  #   ports:
  #     - "8081:8080"
  #   environment:
  #     - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
  #   depends_on:
  #     - kafka

  # transformation:
  #   build:
  #     context: .
  #     dockerfile: docker/Dockerfile-transformation
  #   ports:
  #     - "8082:8080"
  #   environment:
  #     - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
  #   depends_on:
  #     - kafka

  # storage:
  #   build:
  #     context: .
  #     dockerfile: docker/Dockerfile-storage
  #   ports:
  #     - "8083:8080"
  #   environment:
  #     - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
  #   depends_on:
  #     - kafka

  # serving:
  #   build:
  #     context: .
  #     dockerfile: docker/Dockerfile-serving
  #   ports:
  #     - "8084:8080"
  #   environment:
  #     - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
  #   depends_on:
  #     - kafka