FROM openjdk:11-jre-slim

WORKDIR /app

# Copy only the Serving-related code and build configuration
COPY ./serving/src/main/scala/FlinkServingApp.scala /app/serving/src/main/scala/
COPY ./build.sbt /app/
COPY ./scripts/serving-start.sh /app/

# Install sbt (Scala Build Tool)
RUN apt-get update && apt-get install -y curl
RUN curl -Ls https://github.com/sbt/sbt/releases/download/v1.8.2/sbt-1.8.2.tgz | tar xz -C /usr/local && ln -s /usr/local/sbt/bin/sbt /usr/bin/sbt


# Build the project
RUN sbt "project serving" clean compile

# Set the entry point for this service
ENTRYPOINT ["/app/serving-start.sh"]
