FROM openjdk:11-jre-slim

WORKDIR /app

# Copy only the Kafka Producer-related code and build configuration
COPY ./kafka-producer/src/main/scala/KafkaProducerApp.scala /app/kafka-producer/src/main/scala/
COPY ./build.sbt /app/
COPY ./scripts/kafka-producer-start.sh /app/
COPY ./kafka-producer/src/main/resources/ /app/kafka-producer/src/main/resources/

# Install sbt (Scala Build Tool)
RUN apt-get update && apt-get install -y curl
RUN curl -Ls https://github.com/sbt/sbt/releases/download/v1.8.2/sbt-1.8.2.tgz | tar xz -C /usr/local && ln -s /usr/local/sbt/bin/sbt /usr/bin/sbt


# Build the project
RUN sbt "project kafkaProducer" clean compile

# Set the entry point for this service
ENTRYPOINT ["/app/kafka-producer-start.sh"]
